### ISSUE TITLE
在gallley 页面 切换到其他app 再返回时 空指针

### ISSUE THREAD

**Issue by lwj1994** [pengjianbo/GalleryFinal#106]
FATAL EXCEPTION: main
                                                                    Process: com.quxiangtou.app, PID: 15879
                                                                    java.lang.RuntimeException: Unable to destroy activity {com.quxiangtou.app/cn.finalteam.galleryfinal.PhotoSelectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
                                                                        at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
                                                                        at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
                                                                        at android.app.Activity.performDestroy(Activity.java:6422)
                                                                        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
                                                                        at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lwj1994** [comment]
状态恢复的时候出了bug..
