### ISSUE TITLE
Unable to destroy activity 

### ISSUE THREAD

**Issue by gmfbilu** [pengjianbo/GalleryFinal#107]
java.lang.RuntimeException: Unable to destroy activity {com.smzf100.saomatuan/cn.finalteam.galleryfinal.PhotoSelectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3916)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3934)
    at android.app.ActivityThread.access$1400(ActivityThread.java:158)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5506)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
    at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
    at android.app.Activity.performDestroy(Activity.java:6253)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1164)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3903)
    ... 10 more

**Comment by xubenliang** [comment]
同样遇到这问题！
