### ISSUE TITLE
Android 7.0打开相机时报错

### ISSUE THREAD

**Issue by cbiqih** [pengjianbo/GalleryFinal#128]
Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/GalleryFinal/IMG20170214230157.jpg exposed beyond app through ClipData.Item.getUri()
                                                 at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                 at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                 at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                 at android.content.Intent.prepareToLeaveProcess(Intent.java:8923)
                                                 at android.content.Intent.prepareToLeaveProcess(Intent.java:8908)
                                                 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
                                                 at android.app.Activity.startActivityForResult(Activity.java:4288)
                                                 at android.app.Activity.startActivityForResult(Activity.java:4247)
                                                 at cn.finalteam.galleryfinal.PhotoBaseActivity.takePhotoAction(PhotoBaseActivity.java:136)
                                                 at cn.finalteam.galleryfinal.PhotoEditActivity.onCreate(PhotoEditActivity.java:266)
                                                 at android.app.Activity.performCreate(Activity.java:6736)
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722) 
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:154) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:6114) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by 1479HuangDa** [comment]
I  have so

**Comment by xiangbo2015** [comment]
我也是

**Comment by zyhhe** [comment]
![image](https://cloud.githubusercontent.com/assets/15338099/24031204/399093ec-0b1c-11e7-9588-b0fb251e3bcf.png)
解决方法

**Comment by 1479HuangDa** [comment]
thank you so much guys！！！

**Comment by 1479HuangDa** [comment]
大哥 你的是maven项目 我无法修改你的源码

**Comment by juesai2015** [comment]
1. 在AndroidManifest.xml中添加如下代码
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    <application
        ...
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="包名.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>
</manifest>

2. 在res目录下新建一个xml文件夹，并且新建一个provider_paths的xml文件
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>

3. 把
 captureIntent.putExtra(MediaStore.EXTRA_OUTPUT, mTakePhotoUri);
变成：
  int currentapiVersion = Build.VERSION.SDK_INT;
            if (currentapiVersion < 24){
                captureIntent.putExtra(MediaStore.EXTRA_OUTPUT, mTakePhotoUri);
            }else{  //解决Android 7.0 相机问题
                captureIntent.putExtra(MediaStore.EXTRA_OUTPUT, FileProvider.getUriForFile(getApplicationContext(),
                        getApplicationContext().getPackageName()+ ".provider", createImageFile));
            }  //Uri.fromFile(createImageFile)


完成操作 !

**Comment by juesai2015** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    <application
        ...
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>
</manifest>
