### ISSUE TITLE
你好,我在使用你的DemoAPk裁剪的时候,如果图片格式是png会裁剪失败,直接crach,报的是一个空指针异常;jpg格式不会

### ISSUE THREAD

**Issue by linjhak** [pengjianbo/GalleryFinal#130]

**Comment by Allyns** [comment]
我也遇到了这样的问题

**Comment by Allyns** [comment]
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
                                                                 java.io.IOException: Invalid marker: 89
                                                                     at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1837)
                                                                     at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
                                                                     at android.media.ExifInterface.<init>(ExifInterface.java:1112)
                                                                     at cn.finalteam.galleryfinal.widget.crop.CropUtil.getExifRotation(CropUtil.java:59)
                                                                     at cn.finalteam.galleryfinal.widget.crop.CropImageActivity.setSourceUri(CropImageActivity.java:119)
                                                                     at cn.finalteam.galleryfinal.PhotoEditActivity.loadImage(PhotoEditActivity.java:385)
                                                                     at cn.finalteam.galleryfinal.PhotoEditActivity.onCreate(PhotoEditActivity.java:261)
                                                                     at android.app.Activity.performCreate(Activity.java:6745)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2788)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ly469097645** [comment]
这个问题你们解决了没！！！

**Comment by Allyns** [comment]
还没有 解决

**Comment by huaihaizi** [comment]
小米的会有问题

**Comment by zk1393943039** [comment]
将所依赖的剪裁库改成这样 那个版本太低了
compile 'cn.finalteam:toolsfinal:1.+'

**Comment by autoool** [comment]
https://github.com/pengjianbo/ToolsFinal  这个组件的问题。因为他们没人维护了。
```

```

**Comment by autoool** [comment]
@Allyns @ly469097645

**Comment by shiguang1120** [comment]
http://blog.csdn.net/jojo2014jojo/article/details/55059390


```
Uri uri; // the URI you've received from the other app
InputStream in;
try {
  in = getContentResolver().openInputStream(uri);
  ExifInterface exifInterface = new ExifInterface(in);
  // Now you can extract any Exif tag you want
  // Assuming the image is a JPEG or supported raw format
} catch (IOException e) {
  // Handle any errors
} finally {
  if (in != null) {
    try {
      in.close();
    } catch (IOException ignored) {}
  }
}
```

**Comment by Doonkey** [comment]
将android.media.ExifInterface改为android.support.media.ExifInterface
![image](https://user-images.githubusercontent.com/9332309/53297456-18745500-385a-11e9-8e64-a065631b6d2f.png)
![image](https://user-images.githubusercontent.com/9332309/53297468-275b0780-385a-11e9-8f9d-040a2595d1fd.png)
问题解决

**Comment by Allyns** [comment]
@Doonkey  感谢
