### ISSUE TITLE
安卓6.0出现这个错误 

### ISSUE THREAD

**Issue by lanjd** [pengjianbo/GalleryFinal#145]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zjeja/cn.finalteam.galleryfinal.PhotoEditActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
	at android.app.ActivityThread.access$1000(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5628)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
	at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:352)
	at android.app.Activity.requestWindowFeature(Activity.java:3755)
	at cn.finalteam.galleryfinal.widget.crop.CropImageActivity.setupWindowFlags(CropImageActivity.java:82)
	at cn.finalteam.galleryfinal.widget.crop.CropImageActivity.onCreate(CropImageActivity.java:77)
	at cn.finalteam.galleryfinal.PhotoEditActivity.onCreate(PhotoEditActivity.java:198)
	at android.app.Activity.performCreate(Activity.java:6351)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
	... 9 more

**Comment by FizzClown** [comment]
我也是类似的这个错误，我看了下，在调用相机和调用系统相册的时候都会出现空指针的问题，然后打了个断点，是TextView空指针的异常，并不知道哪里出了问题，之前都是好的，demo也是好的，猜测是冲突，但是原因未知

**Comment by lanjd** [comment]
这个错误不太记得了 = = ，好像是，源码里，有个地方 初始化方法位置上下调用下就行了

**Comment by FizzClown** [comment]
private void setTheme() {
      
        mTvTitle.setTextColor(mThemeConfig.getTitleBarTextColor());
       //这句代码有问题  空指针  mTvTitle为空
    }

**Comment by lanjd** [comment]
这个框架问题还挺多了，目前公司的项目还是用这个。。。由于是接手的别人的代码，没办法，不过我已经修复了几个空指针的问题，如果你需要此框架，你可以留下邮箱，我把我改过的源码发你，你以model的形式依赖就行了

**Comment by FizzClown** [comment]
好的，624525825@qq.com   谢谢啦   用的时候不用改什么是吧

**Comment by lanjd** [comment]
应该不用改，我现在没发现有抛什么异常

**Comment by FizzClown** [comment]
谢谢，成功解决了问题，等我有空我看下源码具体什么原因

**Comment by lanjd** [comment]
好的
