### ISSUE TITLE
Nexus5手机6.0拍照崩溃

### ISSUE THREAD

**Issue by YangLzy** [pengjianbo/GalleryFinal#29]
`02-23 09:04:47.016 11327-11327/cn.finalteam.galleryfinal.sample E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 39247812)
02-23 09:04:47.017 11327-11327/cn.finalteam.galleryfinal.sample E/AndroidRuntime: Error reporting crash
                                                                                  android.os.TransactionTooLargeException: data parcel size 39247812 bytes
                                                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                                                      at android.os.BinderProxy.transact(Binder.java:503)
                                                                                      at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
                                                                                      at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)`

**Comment by pengjianbo** [comment]
我用的是Nexus5 6.0.1的系统，好像没有遇到奔溃的问题。请问有全面点的日志吗？

**Comment by lovebobo** [comment]
me too ，，do you have the solution to that?
