### ISSUE TITLE
红米手机note3 拍照崩溃

### ISSUE THREAD

**Issue by weilixing00** [pengjianbo/GalleryFinal#55]
红米note3拍照崩溃  第二次拍照才可以正常显示  报空指针异常  望回复
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhujiajinrong.xg.zhujia/cn.finalteam.galleryfinal.PhotoEditActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
                                                                                 at java.util.LinkedHashMap.<init>(LinkedHashMap.java:132)
                                                                                 at cn.finalteam.galleryfinal.PhotoEditActivity.onRestoreInstanceState(PhotoEditActivity.java:128)
                                                                                 at android.app.Activity.performRestoreInstanceState(Activity.java:982)
                                                                                 at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1168)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                 at android.os.Looper.loop(Looper.java:194) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by Bob-liuboyu** [comment]
我现在也报这个bug，小米3c
