### ISSUE TITLE
小米3c，拍照崩溃，相册选择正常

### ISSUE THREAD

**Issue by Bob-liuboyu** [pengjianbo/GalleryFinal#68]
Process: com.vliti.app, PID: 5633
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vliti.app/cn.finalteam.galleryfinal.PhotoEditActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5269)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
                                                              Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
                                                                 at java.util.LinkedHashMap.<init>(LinkedHashMap.java:132)
                                                                 at cn.finalteam.galleryfinal.PhotoEditActivity.onRestoreInstanceState(PhotoEditActivity.java:128)
                                                                 at android.app.Activity.performRestoreInstanceState(Activity.java:1004)
                                                                 at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1162)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5269) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by ByteRax** [comment]
+1

**Comment by c594701048** [comment]
没有给权限

**Comment by a5394c** [comment]
我是小米note pro,同样的情况，同样的错误，希望能解决

**Comment by lovebobo** [comment]
我是华为mate  也是同样情况  求解决方案

**Comment by Zellerpooh** [comment]
我试着在错误的地方进行一个非空判断，暂时能够使用了，但是不知道具体的原因。
if (null!=getIntent().getSerializableExtra("results")){
            mPhotoTempMap = new LinkedHashMap<>((HashMap<Integer, PhotoTempModel>) getIntent().getSerializableExtra("results"));
        }
