### ISSUE TITLE
java.util.ArrayList.clear()' on a null object reference

### ISSUE THREAD

**Issue by ghost** [pengjianbo/GalleryFinal#76]
java.lang.RuntimeException: Unable to destroy activity {com.baj.leshifu/cn.finalteam.galleryfinal.PhotoSelectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3984)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4002)
    at android.app.ActivityThread.access$1800(ActivityThread.java:165)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5669)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
    at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
    at android.app.Activity.performDestroy(Activity.java:6297)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3971)
    ... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
    at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
    at android.app.Activity.performDestroy(Activity.java:6297)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3971)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4002)
    at android.app.ActivityThread.access$1800(ActivityThread.java:165)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5669)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ghost** [comment]
java.lang.RuntimeException: Unable to destroy activity {com.baj.leshifu/cn.finalteam.galleryfinal.PhotoSelectActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3524)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3542)
    at android.app.ActivityThread.access$1200(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1312)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5166)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:768)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
    at android.app.Activity.performDestroy(Activity.java:5362)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1120)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3511)
    ... 11 more
java.lang.NullPointerException
    at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
    at android.app.Activity.performDestroy(Activity.java:5362)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1120)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3511)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3542)
    at android.app.ActivityThread.access$1200(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1312)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5166)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:768)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ghost** [comment]
上面是oppo 4.3

**Comment by ByteRax** [comment]
+1

**Comment by YijingwanWang** [comment]
+1
