### ISSUE TITLE
红米note 拍照后空指针

### ISSUE THREAD

**Issue by Jensen0618** [pengjianbo/GalleryFinal#96]
红米note2拍照后出现ava.lang.NullPointerException，java.lang.NullPointerException
                                                                   at java.util.LinkedHashMap.<init>(LinkedHashMap.java:132)
                                                                   at cn.finalteam.galleryfinal.PhotoEditActivity.onRestoreInstanceState(PhotoEditActivity.java:128)

完整错误代码如下：
FATAL EXCEPTION: main
                                                               Process: com.jensen.zhzh, PID: 8736
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jensen.zhzh/cn.finalteam.galleryfinal.PhotoEditActivity}: java.lang.NullPointerException
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: java.lang.NullPointerException
                                                                   at java.util.LinkedHashMap.<init>(LinkedHashMap.java:132)
                                                                   at cn.finalteam.galleryfinal.PhotoEditActivity.onRestoreInstanceState(PhotoEditActivity.java:128)
                                                                   at android.app.Activity.performRestoreInstanceState(Activity.java:924)
                                                                   at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by M2y** [comment]
哥们还没处理吗？

**Comment by JakeWang123** [comment]
三星也会出现这个问题，麻烦尽快fix

**Comment by lodgkk** [comment]
这个是有时候会出来,我测试了华为,小米,htc都有可能出现,主要是没判断是否空指针,需要在源码中改

**Comment by AganCN** [comment]
摩托也出现了此问题
