### ISSUE TITLE
functionConfigBuilder.setForceCrop(true);

### ISSUE THREAD

**Issue by XiaoXunLu** [pengjianbo/GalleryFinal#98]
functionConfigBuilder.setForceCrop(true); 报空指针异常

**Comment by XiaoXunLu** [comment]
Process: com.midou.app, PID: 22792
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap cn.finalteam.galleryfinal.widget.crop.RotateBitmap.getBitmap()' on a null object reference
                                                                   at cn.finalteam.galleryfinal.widget.crop.ImageViewTouchBase.setImageRotateBitmapResetBase(ImageViewTouchBase.java:180)
                                                                   at cn.finalteam.galleryfinal.widget.crop.CropImageView.setImageRotateBitmapResetBase(CropImageView.java:27)
                                                                   at cn.finalteam.galleryfinal.widget.crop.ImageViewTouchBase$1.run(ImageViewTouchBase.java:174)
                                                                   at cn.finalteam.galleryfinal.widget.crop.ImageViewTouchBase.onLayout(ImageViewTouchBase.java:106)
                                                                   at cn.finalteam.galleryfinal.widget.crop.CropImageView.onLayout(CropImageView.java:52)
